# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('job_title', models.CharField(default='', max_length=200)),
                ('current_company', models.CharField(max_length=300)),
                ('is_linkedin_connected', models.BooleanField(default=False)),
                ('is_facebook_connected', models.BooleanField(default=False)),
                ('bio', models.TextField()),
                ('photo_url', models.URLField(blank=True, max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
