# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('company_url', models.URLField(blank=True, max_length=400)),
            ],
        ),
    ]
